config/routes.rb
Rails.application.routes.draw do


  resources :posts do
      resources :marks, only: [:new, :create, :destroy]
	   resources :comments
  end
  devise_scope :user do
    root to: "devise/sessions#new"
     resources :comments
    
  end
  

  devise_for :users
  resources :users do
	  	member do
	      get :following, :followers, :follow
	    end
	end

  resources :relationships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/mark.rb
class Mark < ApplicationRecord
	belongs_to :post
	
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_many :marks
	# acts_as_votable

	has_attached_file :image, styles: { medium: "600x300>" }, default_url: "/images/:style/missing.jpg"

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	
	validates :description, presence: true, length: {maximum: 60}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	has_many :posts
  	has_many :comments
  	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  	has_many :followed_users, through: :relationships, source: :followed
	has_many :reverse_relationships, foreign_key: "followed_id",
	                               class_name:  "Relationship",
	                               dependent:   :destroy
	has_many :followers, through: :reverse_relationships, source: :follower
  
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.jpg"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true, length: {maximum: 50}

	# acts_as_voter
	
	def following?(other_user)
		relationships.find_by(followed_id: other_user.id)
	end

	def follow!(other_user)
		relationships.create(followed_id: other_user.id)
	end
	def unfollow!(other_user)
		relationships.find_by(followed_id: other_user.id).destroy!
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user! 
  include ApplicationHelper
  private
  def configure_permitted_parameters
 		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end

  def after_sign_in_path_for(resource)
  	user_path(current_user)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  
  def create
      @comment = current_user.comments.build(comment_params)    
      @comment.save 
     
    respond_to do |format|
      format.html {redirect_to :back}
      format.js {}
    end
  end

  def destroy   
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html {redirect_to :back}
      format.js {}
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:description, :post_id, :user_id)

  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController

	def new
		@post = Post.find(params[:post_id])
		@mark = Mark.new
	end
	def create
		@post = Post.find(params[:post_id])
		@mark = @post.marks.build(mark_params)

		respond_to do |format|
		if @mark.save 
			format.html { redirect_to :back}
			
			else
				
			format.html { render :new }
			end
		end		
	end
	
 
	def destroy   
		@mark = Mark.find_by(id: params[:id],post_id:params[:post_id])
		@mark.destroy

		respond_to do |format|
		format.html {redirect_to :back}
		format.js {}
		end
	end

  private
   

    def mark_params
      params.require(:mark).permit(:user, :like)
    end
	

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_post_user, only: [ :edit, :update, :destroy]

  

 

  def index
    @posts = Post.all
    @comment = Comment.new
    @posts = Post.order(created_at: :desc)
    @mark = Mark.new
  end

  
  def show
    
  end

  
  def new
    @post = Post.new
  end

 
  def edit
  end

  
  def create
    @post = current_user.posts.build(post_params)
    
    respond_to do |format|
      if @post.save
        
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @post.update(post_params)
        
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:description, :image, :user_id)
    end
    def correct_post_user
      unless current_user == @post.user
        redirect_to root_path
      end
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    us_user = User.find(params[:relationship][:followed_id])
    current_user.follow!(us_user)

    respond_to do |format|
    format.html { redirect_to :back }
    format.js
    end
  end

  def destroy
    us_user = Relationship.find(params[:id]).followed
    current_user.unfollow!(us_user)
  
    respond_to do |format|
    format.html { redirect_to :back }
    format.js
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  
  
  def index
    @users = User.all
   
  end
  def follow
    @user = User.find(params[:id])
  end

  def show
    @posts = current_user.posts
   
  end
  def following
    @title = "Following"
    @user = User.find(params[:user_id])
    @users = @user.followed_users
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:user_id])
    @users = @user.followers
    render 'show_follow'
  end
 
  def new
    @user = User.new
    # @comment = Comment.new
  end


  def edit
  end

 
  def create
    @user = User.new(user_params)
    @comment = current_user.comments.build(comment_params)
    respond_to do |format|
      if @user.save
      
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
 
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user?(user)
		user == current_user
	end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment)  do |f| %>
   <div class="text_area field">
 
    <%= f.text_area :description, placeholder: "Add a comment..." %>
    <%= f.submit '', title: "добавить пост", class: "new_btn" %>
  </div>

  <div class="field">   
    <%= f.hidden_field :post_id, :value => post.id %>
  </div>
  
   
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> 
    	<% if user_signed_in?%>
	    	<%=  current_user.name %>
	    	<% else %>
	    	Instagram
    	<% end %>
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render 'layouts/application/navbar' %>
<div class="container">
    <%= yield %>	
</div>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar  navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to'', posts_path,  class: "logo_img"  %>
     
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="navabar-nav navbar-left formul">
        <li class="formli">
          <form action="#"><input placeholder="Поиск"></form>
          <span class="search_ic"></span>
        </li>
      </ul>
      <ul class="navbar-nav navbar-right ">
        <% if user_signed_in? %>
          <li class="navbar-text">
            <%= link_to '', new_post_path, title: 'new post', class: 'new-post' %>
          </li>
          <li class="navbar-text">
            <%= link_to '', users_path, title: 'Самое инетерсное', class: 'user-interes' %>
          </li>
           <li class="navbar-text">
            <%= link_to '', follow_user_path(current_user), class: 'user-show' %>
          </li>    
           <li class="navbar-text">
            <%= link_to '', user_path(current_user), title: 'my profil', class: 'user-icon' %>
          </li>        
          
        <% end %>
      </ul> 
    </div>
  </div>
</nav>

app/views/marks/_form.html.erb
<%= form_for [post,@mark] do |f| %>

	<%= f.hidden_field :user, value: current_user.id %> 
	<%= f.hidden_field :like, value: true %> 
	<label class = "like_index",>
		<%= f.submit '', style: "display: none;" %>
	</label>
<%end %>

app/views/marks/create.html.erb
<h1>Marks#create</h1>
<p>Find me in app/views/marks/create.html.erb</p>

app/views/marks/destroy.html.erb
<h1>Marks#destroy</h1>
<p>Find me in app/views/marks/destroy.html.erb</p>

app/views/marks/new.html.erb
<h1>Marks#new</h1>
<p>Find me in app/views/marks/new.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  
    <%= f.text_field :description, class: "form-control"  %>
  </div>
  <br>
   <div class="field">
      <label class="btn btn-default btn-file">       
       Выбрать файл<%= f.file_field :image, style: "display: none;" %>
    </label>
    
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Создать', class: "btn btn-primary" %>
  </div>
  <br>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>



<div class="row">
			<h5 class="index_title"><strong>Публикации</strong></h5>
    <% @posts.each do |post| %>
		<div class="index_wrap_box">
		    <div class="up_block">
			    <div class="user_img_thumb">
					<%= link_to image_tag post.user.avatar.url(:thumb)%>
				</div>	
				<div class="info_index_box">
					<span class="user_name_index">
						<%= link_to post.user.name, user_path(post.user) %>
					</span>	
	        		<p >
	        			<%= post.description %>
	        		</p>	
					
				</div>    	
		    </div>
		    <div class="wrap_img_box2">
	         	<%= link_to image_tag post.image.url(:medium) %>

		    </div>

		    <div class="comments_box">
		    	<div class="in_like_box">
		    		<span><%= post.marks.size %>&nbsp;&nbsp;отметок&nbsp;&nbsp;&#171;нравится&#187;</span>	
		    	</div>
		    </div>
			<div class="in_box_d">

  				<% post.comments.each do |comment| %>
	  				<div class="wrap_comment">
	  					<div class="name_new_commit">
							<span><b> <%= comment.user.name %>:</b> </span>	
	  						
	  					</div>
						
						<div class="p_comm_des">
							<p> <%= comment.description %></p>

						<% if comment.user == current_user || post.user == current_user %>	
						<%= link_to 'X', comment_path(comment),class: "destroy", method: :delete, data: { confirm: 'Are you sure?' } %>
						<% end %>
						</div>	

					</div>	
				<% end %>					  				
			</div>
 			
	  		<div class="index_add_comment">
		  		<% if current_user.following?(post.user ) or current_user == post.user %>


		  			<div class="index_add_comment_a">
		  				<% unless Mark.find_by(user: current_user.id, post_id: post.id) %>
						<%= render '/marks/form', post: post %>
						<% else %>
							<% post.marks.each do |mark| %>
							<% if mark.user == current_user.id %>
								<%= link_to post_mark_path(post, mark), method: :delete, class: "liked" do %>
									
								<%end %>
								<% end %>
							<% end %>
						<% end %>			
		  			</div>
		  			<div class="index_form_box">
						<%= render '/comments/form.html.erb', comment: @comment, post: post %>	  				
		  			</div>
		  			
				<% end %>
	  		</div>	        
		</div>
    <% end %>
</div>

<br>

app/views/posts/new.html.erb
<div class="col-md-4">

	<h1>Добавить пост</h1>

	<%= render 'form', post: @post %>

	<%= link_to 'Back', posts_path %>
	
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-md-12 border_show_img">
		<div class="wrap_img_show">
			<%= link_to image_tag @post.image.url(:medium)%>			
		</div>
		<div class="wrap_description">
			<div class="user_img_thumb">
				<%= link_to image_tag @post.user.avatar.url(:thumb)%>		
			</div>
			  <%= @post.user.name %>
			<hr>

			 
				<h5 class="h5post">
					<%= @post.description %>			
					
				</h5>
			<div class="comment_box">
				

			</div>	
				<hr>

			<% if current_user.id == @post.user.id %>					
				
				<div class="action_box">
					
					<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %> 
					<%= link_to 'Back', user_path, class: "btn btn-default" %> 
					<%= link_to 'Destroy', @post, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
			<% end %>	
		</div>
	</div>
</div>

app/views/relationship/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationship/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user.following?(user) %>
	<%= render 'unfollow', us_user: user %>
<% else %>
	<%= render 'follow', user: user  %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
<br>
  <div class="field name_user_form">
    
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <label class="btn btn-default btn-file">       
       Выбрать аватар<%= f.file_field  :avatar %> 
    </label>
  
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Редактировать', class: "btn btn-warning" %>
  </div>
 </div> 
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: us_user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-md-4 border_edit">
		<h4>Редактировать имя <br>изменить картинку</h4>
		<br>
	
	
		<h4><%= link_to 'Редактировать все данные ', edit_user_registration_path(current_user) %></h4>	
	</div>
	<div class="col-md-8 border_edit_form">
		<div class="wrap_form1">
			<%= render 'form', user: @user %>			
		</div>
	</div>
</div>

app/views/users/follow.html.erb
<div class="row">
	<div class="col-md-3">
		<h5>Подписчики</h5>
		<% @user.followers.each do |user| %>
		<p>
			<%= link_to user.name, user_path(user) %>
			
		</p>
		<% end %>
	</div>	
	<div class="col-md-3">		
		<h5>Ваши Подписки</h5>
		<% @user.followed_users.each do |user| %>
		<p>
			<%= link_to user.name, user_path(user) %>
			
		</p>
		<% end %>
		
	</div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h4 class="ineresh1">Интересные люди</h4>


  <div class="row">
  	<div class="index_wrap_box">
	    <% @users.each do |user| %>
	    	<div class="user_all_index">
				<div class="user_img_thumb ">
					<%= image_tag user.avatar.url{:thumb} %>				
				</div>
					<p class="name_interest_index">
				        <%= link_to user.name, user_path(user) %>						
					</p>
				<div class="downbox new_class">
					<%= user.posts.count %>

					<a href="#"> Публикация</a>
					<%= user.followers.count %>
					<a href="#">подписчиков</a>
					<%= user.followed_users.count %>
					<a href="#">Подписки:&nbsp;</a>
				</div>
				<div class="index_all_user_box">
					<% unless current_user?(user) %>
					  <div id="follow_form">
					  	<%= render 'follow_form', user: user %>
					  </div>
					<% end %>
					
				</div>
	    	</div>
	      <hr>
	     
	    <% end %>  	
  	</div>
  </div>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-md-4">
		<div class="wrap_image">
		  <%= link_to image_tag @user.avatar.url(:medium)%>			
		</div>				
	</div>
	<div class="col-md-8">
		<div class="upbox">
			<p class="username">

			  <%= @user.name %>
			</p>
			<% if @user == current_user %>
		
			<%= link_to 'Редакитровать профиль', edit_user_path(@user), class: "edit_prof" %> 
			<ul class="dropdown">
			    <li class="dropdown">
			   		 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
			      <ul class="dropdown-menu">
			      
			        <li><a href="#">Отмена</a></li>
			        <li class="divider"></li>
			        <li><%= link_to 'Выйти', destroy_user_session_path, method: :delete %></li>
			      </ul>
			    </li>
			 </ul>			
			<% end %>
		</div>
		<div class="downbox">
			<%= @user.posts.count %>

			<a href="#"> Публикация</a>
			<%= current_user.followers.count %>
			<a href="#">подписчиков</a>
			<%= current_user.followed_users.count %>
			<a href="#">Подписки:&nbsp;</a>
		</div>
	</div>	
</div>
<div class="wrap_button">
	<% unless current_user?(@user) %>
	  <div id="follow_form">
	  	<%= render 'follow_form', user: @user %>
	  </div>
	<% end %>
</div>
<div class="row">
	<% @user.posts.each do |post| %>
		<div class="col-md-4">
			<div class="in_box">
				<div class="wrap_post_img">
					
					<%= link_to image_tag post.image.url(:medium)%>		
								
				</div>	
				<div class="block_like">
					
					<%= link_to post_path(post), class: "like" do %>
						<span><%= post.marks.size %></span>
					<% end %>
					<%= link_to post_path(post), class: "comment" do %>	
						<span><%= post.comments.count %></span>
					<% end %>
					
				</div>
			</div>
		</div> 
	<% end %>
</div>